name = "daily-log-healthcare"
main = "src/index.ts"
compatibility_date = "2025-12-01"

[vars]
HEALTH_DATE_PROP = "Date"
HEALTH_TITLE_PROP = "Name"
DAILY_LOG_DATE_PROP = "Date"
DAILY_LOG_TITLE_PROP = "Name"
DAILY_LOG_MEAL_PHOTOS_PROP = "Meal Photos"
DAILY_LOG_SOURCE_PROP = "Source"
MEAL_PHOTOS_FOLDER_PATH = "/2026_meal"
DROPBOX_CLIENT_ID = "3pa2irxaypyniq5"

[env.production.vars]
HEALTH_DATE_PROP = "Date"
HEALTH_TITLE_PROP = "Name"
DAILY_LOG_DATE_PROP = "Date"
DAILY_LOG_TITLE_PROP = "Name"
DAILY_LOG_MEAL_PHOTOS_PROP = "Meal Photos"
DAILY_LOG_SOURCE_PROP = "Source"
MEAL_PHOTOS_FOLDER_PATH = "/2026_meal"
DROPBOX_CLIENT_ID = "3pa2irxaypyniq5"

[triggers]
crons = ["0 18 * * *"]

[env.production.triggers]
crons = ["0 18 * * *"]
